realme3/3i : fixed compiling
errors were,

../drivers/input/touchscreen/mediatek/hq_green/nt36525/nt36xxx_ext_proc.c:1378:2: error: format '%d' expects argument of type 'int', but argument 5 has type 'size_t' [-Werror=format=]

../drivers/input/touchscreen/mediatek/hq_green/ipio_touch_driver-v1.0.3.8/userspace.c:759:2: error: format '%d' expects argument of type 'int', but argument 4 has type 'size_t' [-Werror=format=]

Line 2964: ../drivers/power/supply/oppo/charger_ic/oppo_bq24190.c:1406:21: error: 'val_buf' may be used uninitialized in this function [-Werror=maybe-uninitialized]
Line 3078: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:636:3: error: format '%d' expects argument of type 'int', but argument 3 has type 'long int' [-Werror=format=]
Line 3081: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:642:3: error: format '%d' expects argument of type 'int', but argument 3 has type 'long int' [-Werror=format=]
Line 3086: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1930:12: error: invalid storage class for function 'oppo_charger_remove'
Line 3089: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1930:1: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
Line 3093: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1935:13: error: invalid storage class for function 'oppo_charger_shutdown'
Line 3096: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1948:1: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
Line 3099: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1955:2: error: initializer element is not constant
Line 3103: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1956:2: error: initializer element is not constant
Line 3107: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1964:19: error: invalid storage class for function 'oppo_charger_init'
Line 3110: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1968:1: error: initializer element is not constant
Line 3113: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1971:20: error: invalid storage class for function 'mtk_charger_exit'
Line 3116: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1971:1: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
Line 3119: ../drivers/power/supply/mediatek/charger/oppo_mt6771_charger.c:1975:1: error: initializer element is not constant
Line 3124: ../include/linux/moduleparam.h:28:3: error: ISO C90 forbids mixed decrgument of type 'unsigned int', but argument 3 has type 'long unsigned int' [-Werror=format=]
Line 3731: ../drivers/misc/mediatek/sensors-1.0/alsps/alsps_factory.c:400:3: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'long unsigned int' [-Werror=format=]
Line 3735: ../drivers/misc/mediatek/sensors-1.0/alsps/alsps_factory.c:474:3: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'long unsigned int' [-Werror=format=]
Line 3138: ../include/linux/compiler-gcc.h:208:45: error: expected declaration or statement at end of input

../drivers/misc/mediatek/pmic/mt6370/mt6370_pmu_charger.c:4442:19: error: function declaration isn't a prototype [-Werror=strict-prototypes]
../drivers/power/supply/oppo/charger_ic/oppo_bq25890h.c:1280:10: error: 'reg_ovp' may be used uninitialized in this function [-Werror=maybe-uninitialized]

../drivers/power/supply/oppo/charger_ic/oppo_bq24190.c:1405:56: error: 'val_buf' undeclared (first use in this function)

../drivers/usb/gadget/function/f_mass_storage.c:2302:13: error: 'struct fsg_common' has no member named 'new_fsg'
  fsg->common->new_fsg = fsg;

../drivers/usb/gadget/function/f_mass_storage.c:2330:13: error: 'struct fsg_common' has no member named 'new_fsg'
  fsg->common->new_fsg = NULL;

........................

 Changes to be committed:
	modified:   Makefile
	modified:   drivers/input/touchscreen/mediatek/hq_green/ipio_touch_driver-v1.0.3.8/userspace.c
	modified:   drivers/input/touchscreen/mediatek/hq_green/nt36525/nt36xxx_ext_proc.c
	modified:   drivers/misc/mediatek/pmic/mt6370/mt6370_pmu_charger.c
	modified:   drivers/misc/mediatek/sensors-1.0/alsps/Makefile
	modified:   drivers/power/supply/mediatek/charger/Makefile
	modified:   drivers/power/supply/oppo/charger_ic/oppo_bq24190.c
	modified:   drivers/power/supply/oppo/charger_ic/oppo_bq25890h.c
	modified:   drivers/usb/gadget/function/f_mass_storage.c
	modified:   kenv.mk

Signed-off-by: vishalk17 <vishalkapadi95@gmail.com>